### ISSUE TITLE
Is it possible to compile this software yet?

### ISSUE THREAD

**Issue by shigutso** [Trouffman/octv_gears_lgp#1]
Hello, it seems that the last update of this project was 2 years ago, but I'd like to know if this is usable in any state. It would be awesome to use LGP on Linux!

I'm on Ubuntu 17.04 x86_64, and when trying to compile, I get this error:

`
/home/vitor/usr/bin/lgp/octv_gears_lgp/src/full_logic-func.c:1361:1: warning: type defaults to ‘int’ in declaration of ‘readstatus’ [-Wimplicit-int]
/home/vitor/usr/bin/lgp/octv_gears_lgp/src/full_logic-func.c:1361:1: warning: parameter names (without types) in function declaration
CMakeFiles/lgp_gears.dir/build.make:62: recipe for target 'CMakeFiles/lgp_gears.dir/src/full_logic-func.c.o' failed
make[2]: *** [CMakeFiles/lgp_gears.dir/src/full_logic-func.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lgp_gears.dir/all' failed
make[1]: *** [CMakeFiles/lgp_gears.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

Am I missing some dependencies?

Thanks in advance!

**Comment by Trouffman** [comment]
Sorry it is not usable as is it was mainly a prototype. I recommend you check out the work by Tolg9009 at this location : https://github.com/tolga9009/elgato-gchd
If you wan to continue the development of the LGP driver I have a lot of the data still laying around but you will need to code some magic :)

**Comment by shigutso** [comment]
I wish I was good at programming, I would certainly try to continue your work...

Oh well, I guess I'll try to trade my LGP for an Elgato HD then!

Thanks for your reply :)
